language: php

php:
- 5.6
- 7.0

sudo: false

env:
  global:
  - DEFAULT=1

matrix:
  fast_finish: true

  include:
  - php: 7.0
    env: PHPCS=1 DEFAULT=0

before_install:
- phpenv rehash
- set +H

install:
- composer self-update
- composer install --prefer-dist --no-interaction --dev

script:
- if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.* ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi
- if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.* ]]; then vendor/bin/phpunit; fi
- if [ $PHPCS = 1 ]; then vendor/bin/phpcs -p --extensions=php --ignore=tests/bootstrap.php --warning-severity=6 --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

after_success:
- bash <(curl -s https://codecov.io/bash)
